service: sls-website 

provider:
  name: aws
  runtime: python3.6
  versionFunctions: false
  stage: dev
  region: ap-south-1

  

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "uploadBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "sns:publish"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"



functions:
  weblink1:
    handler: lambda_functions/get-data.lambda_handler
    memorySize: 128
    description: My function
    events:
        - http:
            path: lambda_functions/get-data
            method: GET
            cors: true

            
  
resources:
  Resources:
      uploadBucket:
          Type: AWS::S3::Bucket
          Properties:
              BucketName: ${self:service}-${self:provider.stage}-uploads
              WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: error.html
     
